### ISSUE TITLE
Add overview diagram showing the MaaS ecosystem

### ISSUE THREAD

**Issue by brylie** [maas-alliance/guide#6]
The MaaS Guide needs images and diagrams. Add an overview diagram to the introduction, so readers can see the scope of the guide/ecosystem.

**Comment by ChristianMaehler** [comment]
Do you have any specific ideas on that? I may start by contributing a static image and explain it in prose. We then may proceed by refering to that picture in the different chapters.

**Comment by brylie** [comment]
Well, use your creative intuition. :-)

We do have a 'starter diagram' showing relationships between technologies/standards:

![MaaS technology ecosystem](https://raw.githubusercontent.com/maas-alliance/docs/master/research/MaaS-technology-ecosystem.png)

An alternative perspective, which is equally important, is to show groupings of organizations who are active in this space.

**Comment by brylie** [comment]
Well, I trust your creative intuition. :-)

We do have a 'starter diagram' showing relationships between technologies/standards:

![MaaS technology ecosystem](https://raw.githubusercontent.com/maas-alliance/docs/master/research/MaaS-technology-ecosystem.png)

An alternative perspective, which is equally important, is to show groupings of organizations who are active in this space.

**Comment by ChristianMaehler** [comment]
Added an ecosystem description and a JPG of the ecosystem. 

TODO
* The JPG should be SVG in future. 
* adding examples
* adding further aspects of the ecosystem
